"""Initial schema with PostGIS

Revision ID: fa112850cbbc
Revises: 
Create Date: 2026-09-14 22:59:09.829037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fa112850cbbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('river', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('capacity_mcm', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dams_id'), 'dams', ['id'], unique=False)
    op.create_index(op.f('ix_dams_name'), 'dams', ['name'], unique=False)
    op.create_index(op.f('ix_dams_river'), 'dams', ['river'], unique=False)
    op.create_index(op.f('ix_dams_state'), 'dams', ['state'], unique=False)
    op.create_table('glacial_lakes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('area_sq_m', sa.Float(), nullable=True),
    sa.Column('estimated_depth_m', sa.Float(), nullable=True),
    sa.Column('estimated_volume_m3', sa.Float(), nullable=True),
    sa.Column('downstream_river', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_date', sa.String(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glacial_lakes_id'), 'glacial_lakes', ['id'], unique=False)
    op.create_index(op.f('ix_glacial_lakes_name'), 'glacial_lakes', ['name'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=True),
    sa.Column('parameter_metadata', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenarios_scenario_id'), 'scenarios', ['scenario_id'], unique=False)
    op.create_table('simulations',
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=True),
    sa.Column('dam_id', sa.String(), nullable=True),
    sa.Column('lake_id', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('requested_model', sa.String(), nullable=True),
    sa.Column('actual_model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('extent_path', sa.String(), nullable=True),
    sa.Column('depth_path', sa.String(), nullable=True),
    sa.Column('velocity_path', sa.String(), nullable=True),
    sa.Column('arrival_path', sa.String(), nullable=True),
    sa.Column('impact_summary_path', sa.String(), nullable=True),
    sa.Column('satellite_validation_path', sa.String(), nullable=True),
    sa.Column('export_package_path', sa.String(), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('error_information', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dam_id'], ['dams.id'], ),
    sa.ForeignKeyConstraint(['lake_id'], ['glacial_lakes.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_index(op.f('ix_simulations_simulation_id'), 'simulations', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_simulation_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_scenarios_scenario_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_glacial_lakes_name'), table_name='glacial_lakes')
    op.drop_index(op.f('ix_glacial_lakes_id'), table_name='glacial_lakes')
    op.drop_table('glacial_lakes')
    op.drop_index(op.f('ix_dams_state'), table_name='dams')
    op.drop_index(op.f('ix_dams_river'), table_name='dams')
    op.drop_index(op.f('ix_dams_name'), table_name='dams')
    op.drop_index(op.f('ix_dams_id'), table_name='dams')
    op.drop_table('dams')
    # ### end Alembic commands ###
