import os
import zipfile
import tempfile
import json
from .vector_export import export_to_shapefile_zip, export_to_kml
from .tabular_export import export_impact_csv
import shutil

def generate_summary_json(sim_state: dict, impact_json_path: str, satellite_json_path: str) -> str:
    sim_id = sim_state.get("simulation_id")
    
    impact_data = {}
    if impact_json_path and os.path.exists(impact_json_path):
        with open(impact_json_path, 'r') as f:
            impact_data = json.load(f)
            
    sat_data = {}
    if satellite_json_path and os.path.exists(satellite_json_path):
        with open(satellite_json_path, 'r') as f:
            sat_data = json.load(f)
            
    summary = {
        "simulation_id": sim_id,
        "hazard_type": sim_state.get("request", {}).get("hazard_type", "DAM_BREAK"),
        "scenario_id": impact_data.get("scenario_id", "Unknown"),
        "scenario_name": "Extreme Hypothetical Stress-Test Scenario",
        "dam_id": sim_state.get("request", {}).get("dam_id"),
        "model_name": "2D Diffusive Wave Baseline Solver",
        "grid_resolution_m": "~300",
        "maximum_depth_m": sim_state.get("results", {}).get("max_depth_m"),
        "maximum_velocity_mps": sim_state.get("results", {}).get("max_velocity_mps"),
        "modeled_flood_area_km2": impact_data.get("flooded_area_km2"),
        "affected_place_count": len(impact_data.get("places", [])),
        "earliest_model_estimated_arrival_min": min([p.get("flood_arrival_minutes", 9999) for p in impact_data.get("places", [])]) if impact_data.get("places") else None,
        "satellite_validation_status": sat_data.get("validation_status", "Not performed"),
        "simulation_status": sim_state.get("status"),
        "provenance": "Generated by JALDRISHTI Simulation Engine",
        "limitations": [
            "Current solver = 2D Diffusive Wave Baseline Solver. It is NOT SPH or Delft3D.",
            "Scenario = Extreme Hypothetical Stress-Test Scenario.",
            "Maximum depth/velocity are model outputs, not validated real-world predictions.",
            "Arrival times are model-estimated flood arrival times. They are NOT operational warnings.",
            "Satellite validation is observational reference information, not proof that the baseline solver is physically exact.",
            "Simulation domain must not be described as the predicted flood boundary."
        ]
    }
    
    out_path = os.path.join(tempfile.gettempdir(), f"{sim_id}_simulation_summary.json")
    with open(out_path, 'w') as f:
        json.dump(summary, f, indent=4)
        
    return out_path

def generate_readme(sim_state: dict, summary: dict) -> str:
    sim_id = sim_state.get("simulation_id")
    content = f"""JALDRISHTI SIMULATION EXPORT
=============================
Simulation ID: {sim_id}
Hazard Type: {summary.get('hazard_type')}
Scenario: {summary.get('scenario_name')}
Solver Identity: {summary.get('model_name')}

CONTENTS:
- flood_extent/: Contains GeoJSON, KML, and ESRI Shapefile representations of the flood boundary (EPSG:32643 / EPSG:4326).
- rasters/: Contains GeoTIFF files for Maximum Depth (metres) and Arrival Time (seconds since breach). Preserves original CRS and affine transform.
- impact/: Contains tabular and JSON data of affected places and infrastructure.
- simulation_summary.json: Aggregated metrics.

SCIENTIFIC LIMITATIONS & GUARDRAILS:
{chr(10).join(['- ' + l for l in summary.get('limitations', [])])}
"""
    out_path = os.path.join(tempfile.gettempdir(), f"{sim_id}_README.txt")
    with open(out_path, 'w') as f:
        f.write(content)
    return out_path

def export_full_package(sim_state: dict) -> str:
    sim_id = sim_state.get("simulation_id")
    results = sim_state.get("results", {})
    
    pkg_dir = tempfile.mkdtemp(prefix=f"pkg_{sim_id}_")
    base_name = f"JALDRISHTI_{sim_id}"
    root_dir = os.path.join(pkg_dir, base_name)
    
    # Create structure
    os.makedirs(os.path.join(root_dir, "flood_extent"))
    os.makedirs(os.path.join(root_dir, "rasters"))
    os.makedirs(os.path.join(root_dir, "impact"))
    
    # Generate vectors
    extent_path = results.get("extent_path")
    if extent_path and os.path.exists(extent_path):
        shutil.copy(extent_path, os.path.join(root_dir, "flood_extent", "flood_extent.geojson"))
        try:
            kml_path = export_to_kml(extent_path, sim_id)
            shutil.copy(kml_path, os.path.join(root_dir, "flood_extent", "flood_extent.kml"))
        except Exception:
            pass
        try:
            shp_zip = export_to_shapefile_zip(extent_path, sim_id)
            shutil.copy(shp_zip, os.path.join(root_dir, "flood_extent", "flood_extent_shapefile.zip"))
        except Exception:
            pass
            
    # Copy rasters
    depth_path = results.get("depth_path")
    arrival_path = results.get("arrival_path")
    if depth_path and os.path.exists(depth_path):
        shutil.copy(depth_path, os.path.join(root_dir, "rasters", "flood_depth.tif"))
    if arrival_path and os.path.exists(arrival_path):
        shutil.copy(arrival_path, os.path.join(root_dir, "rasters", "arrival_time.tif"))
        
    # Generate impact
    impact_json = results.get("impact_summary_path")
    if impact_json and os.path.exists(impact_json):
        shutil.copy(impact_json, os.path.join(root_dir, "impact", "affected_places.json"))
        try:
            csv_path = export_impact_csv(impact_json, sim_id)
            shutil.copy(csv_path, os.path.join(root_dir, "impact", "affected_places.csv"))
        except Exception:
            pass
            
    # Generate Summary and README
    summary_path = generate_summary_json(sim_state, impact_json, results.get("satellite_validation_path"))
    shutil.copy(summary_path, os.path.join(root_dir, "simulation_summary.json"))
    
    with open(summary_path, 'r') as f:
        summary_obj = json.load(f)
    readme_path = generate_readme(sim_state, summary_obj)
    shutil.copy(readme_path, os.path.join(root_dir, "README.txt"))
    
    # Zip everything
    zip_path = os.path.join(tempfile.gettempdir(), f"{base_name}.zip")
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(root_dir):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, pkg_dir)
                zipf.write(file_path, arcname=arcname)
                
    return zip_path
